sonar.projectKey=leonardopardo045_pae
sonar.organization=leonardopardo045
sonar.projectName=PAE

sonar.sources=backend/services
sonar.tests=backend/services

sonar.test.inclusions=**/src/tests/**/*.js
sonar.exclusions=**/src/tests/**,**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/uploads/**

sonar.javascript.lcov.reportPaths=backend/services/**/coverage/lcov.info

sonar.sourceEncoding=UTF-8
