sonar.projectKey=leonardopardo045_pae
sonar.organization=leonardopardo045
sonar.projectName=PAE_Completo

sonar.sources=backend/services
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
**/node_modules/**,\
**/coverage/**,\
**/dist/**,\
**/build/**,\
**/uploads/**,\
**/src/tests/**
